layouts_dir: _jekyll/_layouts
includes_dir: _jekyll/_includes
destination: _jekyll/_site

exclude:
  - resources
  - package.json
  - package-lock.json
  - readme.md
  - AGENTS.md
  - LICENSE
  - bs-config.js
